global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using System.ComponentModel.DataAnnotations;
global using CommonBasicLibraries.CollectionClasses;
global using MealPlanner.CoreLibrary.Models;
global using aa1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.ApplicationPath;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using jj1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.FileHelpers;
global using CommonBasicLibraries.BasicUIProcesses;
global using MealPlanner.CoreLibrary.Services;
global using MealPlanner.CoreLibrary.Storage;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.MapHelpers;
global using Microsoft.AspNetCore.Components;
global using BasicBlazorLibrary.Components.AutoCompleteHelpers;
global using BasicBlazorLibrary.Components.ComboTextboxes;
global using MealPlanner.CoreLibrary.ViewModels;
global using rr1 = BasicBlazorLibrary.Components.CssGrids.RowColumnHelpers;
global using BasicBlazorLibrary.Components.BaseClasses;
global using cc1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using System.Diagnostics.CodeAnalysis;