global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using System.ComponentModel.DataAnnotations;
global using CommonBasicLibraries.CollectionClasses;
global using MealPlanner.CoreLibrary.Models;
global using aa = CommonBasicLibraries.BasicDataSettingsAndProcesses.ApplicationPath;
global using bb = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using ff = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using jj = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.FileHelpers;
global using CommonBasicLibraries.BasicUIProcesses;
global using MealPlanner.CoreLibrary.Services;
global using MealPlanner.CoreLibrary.Storage;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.MapHelpers;

//global using dd = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions.Dates;